name: carpool_coordinator
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.10.16
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - bcrypt==4.2.1
      - blinker==1.9.0
      - certifi==2025.1.31
      - click==8.1.8
      - colorama==0.4.6
      - dnspython==2.7.0
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - flask==3.1.0
      - flask-bcrypt==1.0.1
      - flask-cors==5.0.1
      - flask-jwt-extended==4.7.1
      - googlemaps==4.10.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyjwt==2.10.1
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.45.3
      - typer==0.15.1
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
      - watchfiles==1.0.4
      - websockets==14.2
      - werkzeug==3.1.3